name: Bot Scalper MT5

on:
  schedule:
    - cron: '0 */4 * * 1-5'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: windows-latest

    steps:
    - name: Récupérer le code
      uses: actions/checkout@v4

    - name: Configurer Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Telecharger et Installer MetaTrader 5
      shell: powershell
      run: |
        Invoke-WebRequest -Uri "https://download.mql5.com/cdn/web/metaquotes.software.corp/mt5/mt5setup.exe" -OutFile "mt5setup.exe"
        Start-Process -FilePath ".\mt5setup.exe" -ArgumentList "/auto" -Wait

    - name: Installer les dependances Python
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install MetaTrader5

    - name: Executer le bot
      env:
        MT5_LOGIN: ${{ secrets.MT5_LOGIN }}
        MT5_PASSWORD: ${{ secrets.MT5_PASSWORD }}
        MT5_SERVER: ${{ secrets.MT5_SERVER }}
      run: |
        python main.py
